import { createEnv } from '@t3-oss/env-core';
import { z } from 'zod';

export const env = createEnv({
    server: {
        PORT: z.coerce.number().default(8080),
        SPAPI_REFRESH_TOKEN: z.string(),
        SPAPI_CLIENT_ID: z.string(),
        SPAPI_APP_CLIENT_SECRET: z.string(),
        CLERK_SECRET_KEY: z.string().min(1, 'CLERK_SECRET_KEY is required'),
        CLERK_PUBLISHABLE_KEY: z.string().min(1, 'CLERK_PUBLISHABLE_KEY is required'),
        CLERK_JWT_KEY: z.string().min(1, 'CLERK_JWT_KEY is required'),
        CLERK_ISSUER: z.string().url('CLERK_ISSUER must be a URL'),
        CLERK_AUTHORIZED_PARTIES: z.string().min(1, 'CLERK_AUTHORIZED_PARTIES is required'),
        CLERK_WEBHOOK_SIGNING_SECRET: z.string().min(1, 'CLERK_WEBHOOK_SIGNING_SECRET is required'),
        ADMIN_MERCHBASE_USER_ID: z.string().startsWith('mbu_').optional(),
        KEEPA_API_KEY: z.string().optional(),
        GEMINI_API_KEY: z.string().optional(),
        DEV_CLERK_SIGN_IN_USER_ID: z.string().optional(),
        DISABLE_SERVER_JOB_RUNNER: z.stringbool().default(false),
        DATABASE_MIGRATION_TARGET: z.enum(['pre-cutover', 'latest']).default('pre-cutover'),
        DATABASE_HOST: z.string().optional(),
        DATABASE_PORT: z.coerce.number().optional(),
        DATABASE_NAME: z.string().optional(),
        DATABASE_USER: z.string().optional(),
        DATABASE_PASSWORD: z.string().optional(),
    },
    runtimeEnv: {
        PORT: process.env.PORT,
        SPAPI_REFRESH_TOKEN: process.env.SPAPI_REFRESH_TOKEN,
        SPAPI_CLIENT_ID: process.env.SPAPI_CLIENT_ID,
        SPAPI_APP_CLIENT_SECRET: process.env.SPAPI_APP_CLIENT_SECRET,
        CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
        CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY,
        CLERK_JWT_KEY: process.env.CLERK_JWT_KEY,
        CLERK_ISSUER: process.env.CLERK_ISSUER,
        CLERK_AUTHORIZED_PARTIES: process.env.CLERK_AUTHORIZED_PARTIES,
        CLERK_WEBHOOK_SIGNING_SECRET: process.env.CLERK_WEBHOOK_SIGNING_SECRET,
        ADMIN_MERCHBASE_USER_ID: process.env.ADMIN_MERCHBASE_USER_ID,
        KEEPA_API_KEY: process.env.KEEPA_API_KEY,
        GEMINI_API_KEY: process.env.GEMINI_API_KEY,
        DEV_CLERK_SIGN_IN_USER_ID: process.env.DEV_CLERK_SIGN_IN_USER_ID,
        DISABLE_SERVER_JOB_RUNNER: process.env.DISABLE_SERVER_JOB_RUNNER,
        DATABASE_MIGRATION_TARGET: process.env.DATABASE_MIGRATION_TARGET,
        DATABASE_HOST: process.env.DATABASE_HOST,
        DATABASE_PORT: process.env.DATABASE_PORT,
        DATABASE_NAME: process.env.DATABASE_NAME,
        DATABASE_USER: process.env.DATABASE_USER,
        DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
    },
});
