import { LICENSE_KEY_ENV_VAR } from './cli-auth';
import type { CliPaths } from './cli-config';

const DEFAULT_MARKETPLACE_ID = 'ATVPDKIKX0DER';

export const printUsage = (paths: CliPaths) => {
    const usage = [
        'NAME',
        '  rw, rankwrangler - RankWrangler command line interface',
        '',
        'SYNOPSIS',
        '  rw --version',
        '  rankwrangler --version',
        '  rw changelog',
        '  rankwrangler changelog',
        '  rw <resource> <verb> [args...] [options]',
        '  rankwrangler <resource> <verb> [args...] [options]',
        '',
        'COMMANDS',
        '  changelog',
        '  products get <ASIN>',
        '  products summary <ASIN>',
        '  products history <ASIN>',
        '  operations get <operationId>',
        '  catalog search <term>',
        '  catalog query <term>',
        '  catalog run <runId>',
        '  catalog runs <queryId>',
        '  license status',
        '  license validate',
        '  auth status',
        '  auth set [licenseKey]',
        '  auth set --stdin',
        '  auth clear',
        '  config show',
        '  config get <key>',
        '  config set base-url <origin>',
        '  config set marketplace <marketplaceId>',
        '  config set storage-dir <path>',
        '  config unset <key>',
        '  config reset',
        '',
        'OPTIONS',
        '  -h, --help               Show this help message',
        '  --version                Print the CLI version',
        '  --baseUrl <origin>       Override API origin',
        `  -m, --marketplace <id>   Override marketplace (default: ${DEFAULT_MARKETPLACE_ID})`,
        '  --asin <ASIN>            Add ASIN (repeatable)',
        '  --metrics <list>         History metrics: bsr,price (default: bsr,price)',
        '  --bucket <unit>          History buckets: auto,day,week,month (default: auto)',
        '  --days <N>               History lookback window (30-3650, default: 365)',
        '  --startAt <ISO>          History range start (ISO date/time)',
        '  --endAt <ISO>            History range end (ISO date/time)',
        '  --limit <N>              History point or Catalog page limit',
        '  --maxAgeSeconds <N>      Catalog reuse age (0-604800, default: 86400)',
        '  --cursor <runId>          Continue Catalog run-history pagination',
        '  --stdin                  Read auth secret from standard input',
        '',
        'FILES',
        `  ${paths.configPath}           Active CLI config`,
        `  ${paths.globalConfigPath}           Global CLI settings`,
        '',
        'ENVIRONMENT',
        `  ${LICENSE_KEY_ENV_VAR}           License key override for CI/automation`,
        '  RR_API_URL               API origin fallback',
        '  RR_MARKETPLACE_ID        Marketplace fallback',
        '  RR_STORAGE_DIR           Storage directory override',
        '  RR_ASIN                  Single ASIN fallback',
        '  RR_ASINS                 Comma-separated ASIN fallback',
        '  RR_HISTORY_METRICS       Comma-separated history metrics fallback',
        '',
        'EXAMPLES',
        '  rw auth set rrk_...',
        '  printf %s "$RR_LICENSE_KEY" | rw auth set --stdin',
        `  ${LICENSE_KEY_ENV_VAR}=rrk_... rw products get B0DV53VS61`,
        '  RR_STORAGE_DIR=~/.config/rankwrangler rw config show',
        '  rw --version',
        '  rw changelog',
        '  rw config get marketplace',
        '  rw config set storage-dir ~/.config/rankwrangler',
        '  rw config unset marketplace',
        '  rw products summary B0DV53VS61',
        '  rw products get B0DV53VS61 --metrics bsr,price --bucket week',
        '  rw products history B0DV53VS61 --metrics bsr,price --bucket week',
        '  rw operations get 11111111-1111-4111-8111-111111111111',
        '  rw catalog search "retro gardening shirt" --maxAgeSeconds 0',
        '  rw catalog query "retro gardening shirt"',
        '  rw catalog run 22222222-2222-4222-8222-222222222222',
        '  rw catalog runs 11111111-1111-4111-8111-111111111111 --limit 20',
        '  rw products history B0DV53VS61 --startAt 2025-01-01 --endAt 2025-12-31 --bucket month',
        '  rankwrangler license status',
    ];

    console.log(usage.join('\n'));
};
