import { API_KEY_ENV_VAR } from './cli-auth';
import type { CliPaths } from './cli-config';

const DEFAULT_MARKETPLACE_ID = 'ATVPDKIKX0DER';

export const printUsage = (paths: CliPaths) => {
    const usage = [
        'NAME',
        '  rw, rankwrangler - RankWrangler command line interface',
        '',
        'SYNOPSIS',
        '  rw --version',
        '  rankwrangler --version',
        '  rw changelog',
        '  rankwrangler changelog',
        '  rw <resource> <verb> [args...] [options]',
        '  rankwrangler <resource> <verb> [args...] [options]',
        '',
        'COMMANDS',
        '  changelog',
        '  product get <ASIN...>',
        '  product search <keyword>',
        '  product history <ASIN>',
        '  keyword get <keyword>',
        '  keyword search <text>',
        '  keyword history <keyword>',
        '  auth status',
        '  auth set [apiKey]',
        '  auth set --stdin',
        '  auth clear',
        '  config show',
        '  config get <key>',
        '  config set base-url <origin>',
        '  config set marketplace <marketplaceId>',
        '  config set storage-dir <path>',
        '  config unset <key>',
        '  config reset',
        '',
        'OPTIONS',
        '  -h, --help               Show this help message',
        '  --version                Print the CLI version',
        '  --baseUrl <origin>       Override API origin',
        `  -m, --marketplace <id>   Override marketplace (default: ${DEFAULT_MARKETPLACE_ID})`,
        '  --refresh                Product search refresh (separate Search contract)',
        '  --metrics <list>         Product history metrics: salesRank,price (default: salesRank,price)',
        '  --bucket <unit>          Product history buckets: auto,day,week,month (default: auto)',
        '  --days <N>               Product history lookback (30-3650, default: 365)',
        '  --rangeDays <N>          Keyword history lookback (7-365, default: 90)',
        '  --startAt <ISO>          Product history range start (ISO date/time)',
        '  --endAt <ISO>            Product history range end (ISO date/time)',
        '  --limit <N>              Result limit',
        '  --cursor <N>             Keyword search offset (default: 0)',
        '  --stdin                  Read auth secret from standard input',
        '',
        'FILES',
        `  ${paths.configPath}           Active CLI config`,
        `  ${paths.globalConfigPath}           Global CLI settings`,
        '',
        'ENVIRONMENT',
        `  ${API_KEY_ENV_VAR}           Merchbase API key override for CI/automation`,
        '  RR_API_URL               API origin fallback',
        '  RR_MARKETPLACE_ID        Marketplace fallback',
        '  RR_STORAGE_DIR           Storage directory override',
        '  RR_HISTORY_METRICS       Comma-separated product history metrics fallback',
        '',
        'EXAMPLES',
        '  rw auth set ak_...',
        '  printf %s "$MERCHBASE_API_KEY" | rw auth set --stdin',
        `  ${API_KEY_ENV_VAR}=ak_... rw product get B0DV53VS61`,
        '  rw product get B0DV53VS61 B012345678',
        '  rw product search "retro gardening shirt"',
        '  rw product history B0DV53VS61 --bucket week',
        '  rw keyword get "retro gardening shirt"',
        '  rw keyword search "retro gardening" --limit 10',
        '  rw keyword history "retro gardening shirt" --rangeDays 90',
        '  RR_STORAGE_DIR=~/.config/rankwrangler rw config show',
        '  rw --version',
        '  rw changelog',
        '  rankwrangler auth status',
    ];

    console.log(usage.join('\n'));
};
