// Generated by dts-bundle-generator v9.5.1

export interface LicenseUsageData {
	id: string;
	email: string;
	usage: number;
	usageLimit: number;
}
export interface ClerkUser {
	sub: string;
	email?: string;
}
export interface ContextRequest {
	headers: {
		authorization?: string;
		host?: string;
	};
}
export type ProductInfo = {
	asin: string;
	marketplaceId: string;
	dateFirstAvailable: string | null;
	title: string | null;
	brand: string | null;
	isMerchListing: boolean;
	bullet1: string | null;
	bullet2: string | null;
	rootCategoryId: number | null;
	rootCategoryBsr: number | null;
	rootCategoryDisplayName: string | null;
	thumbnailUrl?: string;
	keepa: {
		fetchedAt: string;
		sourceUpdatedAt: string | null;
		firstTrackedAt: string | null;
		rootCategoryId: number | null;
		currentRootCategoryBsr: number | null;
		currentNewPrice: {
			amountMinor: number;
			currencyCode: string;
		} | null;
		monthlySold: number | null;
		averageRootCategoryBsr30: number | null;
		averageRootCategoryBsr90: number | null;
		salesRankDrops: {
			days30: number | null;
			days90: number | null;
			days180: number | null;
			days365: number | null;
		};
	} | null;
	metadata: {
		spApiFetchedAt: string | null;
		cached: boolean;
	};
};
declare const operationTypes: readonly [
	"productHistoryRefresh",
	"catalogSearch"
];
export type ProductHistoryResource = {
	type: "productHistory";
	marketplaceId: string;
	asin: string;
};
export type CatalogSearchResource = {
	type: "catalogSearchRun";
	queryId: string;
	runId: string;
};
export type OperationError = {
	code: "PROVIDER_UNAVAILABLE" | "RESOURCE_NOT_FOUND" | "INTERNAL_ERROR";
	message: string;
};
export type PublicOperationType = (typeof operationTypes)[number];
export type PublicOperation = {
	id: string;
	type: PublicOperationType;
	status: "pending";
	retryAfterSeconds: 2;
	createdAt: string;
	updatedAt: string;
} | {
	id: string;
	type: "productHistoryRefresh";
	status: "completed";
	resource: ProductHistoryResource;
	error: null;
	createdAt: string;
	updatedAt: string;
	completedAt: string;
} | {
	id: string;
	type: "catalogSearch";
	status: "completed";
	resource: CatalogSearchResource;
	error: null;
	createdAt: string;
	updatedAt: string;
	completedAt: string;
} | {
	id: string;
	type: PublicOperationType;
	status: "completed";
	resource: null;
	error: OperationError;
	createdAt: string;
	updatedAt: string;
	completedAt: string;
};
declare const productHistoryBuckets: readonly [
	"auto",
	"day",
	"week",
	"month"
];
export type ProductHistoryBucket = (typeof productHistoryBuckets)[number];
export type ResolvedHistoryBucket = Exclude<ProductHistoryBucket, "auto">;
export type HistoryBucketTuple = [
	string,
	number | null
];
export type HistoryBucketSummary = {
	first: number | null;
	latest: number | null;
	min: number | null;
	max: number | null;
	count: number;
	firstBucketAt: string | null;
	latestBucketAt: string | null;
};
export type AgentHistorySeries = {
	bsr?: {
		unit: "rank";
		category: {
			id: number;
			name: string | null;
		} | null;
		buckets: HistoryBucketTuple[];
		summary: HistoryBucketSummary;
	};
	price?: {
		unit: "minorCurrency";
		currencyCode: "USD";
		valueScale: 100;
		buckets: HistoryBucketTuple[];
		summary: HistoryBucketSummary;
	};
};
export type AgentHistoryResponse = {
	schemaVersion: 2;
	marketplaceId: string;
	asin: string;
	status: "collecting" | "ready" | "empty";
	latestImportAt: string | null;
	syncTriggered: boolean;
	operation: PublicOperation | null;
	range: {
		startAt: string;
		endAt: string;
		bucket: ResolvedHistoryBucket;
	};
	series: AgentHistorySeries;
};
export type ProductHistoryError = {
	schemaVersion: 2;
	status: "error";
	latestImportAt: null;
	syncTriggered: false;
	operation: PublicOperation | null;
	range: {
		startAt: string;
		endAt: string;
		bucket: "day" | "week" | "month";
	};
	series: {};
	error: {
		code: string;
		message: string;
	};
};
export type ProductReadModel = {
	schemaVersion: 1;
	marketplaceId: string;
	asin: string;
	status: "ready" | "partial";
	summary: ProductInfo;
	history: AgentHistoryResponse | ProductHistoryError;
};
export declare const publicAppRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: {
		user: ClerkUser;
		isAdmin: boolean;
		authType: "license" | "clerk" | "none";
		authExpiresAtMs: null;
		license: {
			key: string;
			data: LicenseUsageData | undefined;
		};
		licenseError: undefined;
		request: ContextRequest;
	} | {
		user: null;
		isAdmin: boolean;
		authType: "license" | "clerk" | "none";
		authExpiresAtMs: null;
		license: null;
		licenseError: string | undefined;
		request: ContextRequest;
	} | {
		user: ClerkUser;
		isAdmin: boolean;
		authType: "license" | "clerk" | "none";
		authExpiresAtMs: number;
		license: null;
		licenseError: undefined;
		request: ContextRequest;
	};
	meta: object;
	errorShape: import("@trpc/server").TRPCDefaultErrorShape;
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	api: import("@trpc/server").TRPCBuiltRouter<{
		ctx: {
			user: ClerkUser;
			isAdmin: boolean;
			authType: "license" | "clerk" | "none";
			authExpiresAtMs: null;
			license: {
				key: string;
				data: LicenseUsageData | undefined;
			};
			licenseError: undefined;
			request: ContextRequest;
		} | {
			user: null;
			isAdmin: boolean;
			authType: "license" | "clerk" | "none";
			authExpiresAtMs: null;
			license: null;
			licenseError: string | undefined;
			request: ContextRequest;
		} | {
			user: ClerkUser;
			isAdmin: boolean;
			authType: "license" | "clerk" | "none";
			authExpiresAtMs: number;
			license: null;
			licenseError: undefined;
			request: ContextRequest;
		};
		meta: object;
		errorShape: import("@trpc/server").TRPCDefaultErrorShape;
		transformer: false;
	}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
		public: import("@trpc/server").TRPCBuiltRouter<{
			ctx: {
				user: ClerkUser;
				isAdmin: boolean;
				authType: "license" | "clerk" | "none";
				authExpiresAtMs: null;
				license: {
					key: string;
					data: LicenseUsageData | undefined;
				};
				licenseError: undefined;
				request: ContextRequest;
			} | {
				user: null;
				isAdmin: boolean;
				authType: "license" | "clerk" | "none";
				authExpiresAtMs: null;
				license: null;
				licenseError: string | undefined;
				request: ContextRequest;
			} | {
				user: ClerkUser;
				isAdmin: boolean;
				authType: "license" | "clerk" | "none";
				authExpiresAtMs: number;
				license: null;
				licenseError: undefined;
				request: ContextRequest;
			};
			meta: object;
			errorShape: import("@trpc/server").TRPCDefaultErrorShape;
			transformer: false;
		}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
			catalog: import("@trpc/server").TRPCBuiltRouter<{
				ctx: {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: {
						key: string;
						data: LicenseUsageData | undefined;
					};
					licenseError: undefined;
					request: ContextRequest;
				} | {
					user: null;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: null;
					licenseError: string | undefined;
					request: ContextRequest;
				} | {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: number;
					license: null;
					licenseError: undefined;
					request: ContextRequest;
				};
				meta: object;
				errorShape: import("@trpc/server").TRPCDefaultErrorShape;
				transformer: false;
			}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
				search: import("@trpc/server").TRPCMutationProcedure<{
					input: {
						term: string;
						maxAgeSeconds?: number | undefined;
					};
					output: {
						status: "ready";
						run: {
							query: {
								id: string;
								source: "keepa";
								marketplaceId: string;
								normalizedTerm: string;
								displayTerm: string;
								page: number;
							};
							results: {
								productId: string;
								position: {
									source: "keepa";
									value: number;
								};
								observed: {
									rootCategoryBsr: number | null;
									newPriceAmountMinor: number | null;
									currencyCode: "USD";
									monthlySold: number | null;
									averageRootCategoryBsr30: number | null;
									averageRootCategoryBsr90: number | null;
									salesRankDrops: {
										days30: number | null;
										days90: number | null;
										days180: number | null;
										days365: number | null;
									};
									sourceUpdatedAt: string | null;
								};
								currentProduct: ProductInfo | null;
							}[];
							id: string;
							sourceStartedAt: string;
							sourceCompletedAt: string;
							resultCount: number;
							normalizerVersion: number;
							createdAt: string;
						};
						readonly operation?: undefined;
					} | {
						status: "pending";
						operation: PublicOperation;
						run?: undefined;
					};
					meta: object;
				}>;
				query: import("@trpc/server").TRPCBuiltRouter<{
					ctx: {
						user: ClerkUser;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: null;
						license: {
							key: string;
							data: LicenseUsageData | undefined;
						};
						licenseError: undefined;
						request: ContextRequest;
					} | {
						user: null;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: null;
						license: null;
						licenseError: string | undefined;
						request: ContextRequest;
					} | {
						user: ClerkUser;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: number;
						license: null;
						licenseError: undefined;
						request: ContextRequest;
					};
					meta: object;
					errorShape: import("@trpc/server").TRPCDefaultErrorShape;
					transformer: false;
				}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
					get: import("@trpc/server").TRPCQueryProcedure<{
						input: {
							term: string;
						};
						output: {
							id: string;
							source: "keepa";
							marketplaceId: string;
							normalizedTerm: string;
							displayTerm: string;
							page: number;
							tracking: {
								enabled: boolean;
								trackedAt: string | null;
							};
							latestSuccessfulCompletionAt: string | null;
							latestRun: {
								id: string;
								sourceStartedAt: string;
								sourceCompletedAt: string;
								resultCount: number;
								normalizerVersion: number;
								createdAt: string;
							} | null;
						};
						meta: object;
					}>;
					track: import("@trpc/server").TRPCMutationProcedure<{
						input: {
							term: string;
						};
						output: {
							id: string;
							tracking: {
								enabled: boolean;
								trackedAt: string | null;
							};
						};
						meta: object;
					}>;
					untrack: import("@trpc/server").TRPCMutationProcedure<{
						input: {
							term: string;
						};
						output: {
							id: string;
							tracking: {
								enabled: boolean;
								trackedAt: string | null;
							};
						};
						meta: object;
					}>;
				}>>;
				run: import("@trpc/server").TRPCBuiltRouter<{
					ctx: {
						user: ClerkUser;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: null;
						license: {
							key: string;
							data: LicenseUsageData | undefined;
						};
						licenseError: undefined;
						request: ContextRequest;
					} | {
						user: null;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: null;
						license: null;
						licenseError: string | undefined;
						request: ContextRequest;
					} | {
						user: ClerkUser;
						isAdmin: boolean;
						authType: "license" | "clerk" | "none";
						authExpiresAtMs: number;
						license: null;
						licenseError: undefined;
						request: ContextRequest;
					};
					meta: object;
					errorShape: import("@trpc/server").TRPCDefaultErrorShape;
					transformer: false;
				}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
					get: import("@trpc/server").TRPCQueryProcedure<{
						input: {
							id: string;
						};
						output: {
							query: {
								id: string;
								source: "keepa";
								marketplaceId: string;
								normalizedTerm: string;
								displayTerm: string;
								page: number;
							};
							results: {
								productId: string;
								position: {
									source: "keepa";
									value: number;
								};
								observed: {
									rootCategoryBsr: number | null;
									newPriceAmountMinor: number | null;
									currencyCode: "USD";
									monthlySold: number | null;
									averageRootCategoryBsr30: number | null;
									averageRootCategoryBsr90: number | null;
									salesRankDrops: {
										days30: number | null;
										days90: number | null;
										days180: number | null;
										days365: number | null;
									};
									sourceUpdatedAt: string | null;
								};
								currentProduct: ProductInfo | null;
							}[];
							id: string;
							sourceStartedAt: string;
							sourceCompletedAt: string;
							resultCount: number;
							normalizerVersion: number;
							createdAt: string;
						};
						meta: object;
					}>;
					list: import("@trpc/server").TRPCQueryProcedure<{
						input: {
							queryId: string;
							limit?: number | undefined;
							cursor?: string | undefined;
						};
						output: {
							items: {
								id: string;
								sourceStartedAt: string;
								sourceCompletedAt: string;
								resultCount: number;
								normalizerVersion: number;
								createdAt: string;
							}[];
							nextCursor: string | null;
						};
						meta: object;
					}>;
				}>>;
			}>>;
			product: import("@trpc/server").TRPCBuiltRouter<{
				ctx: {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: {
						key: string;
						data: LicenseUsageData | undefined;
					};
					licenseError: undefined;
					request: ContextRequest;
				} | {
					user: null;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: null;
					licenseError: string | undefined;
					request: ContextRequest;
				} | {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: number;
					license: null;
					licenseError: undefined;
					request: ContextRequest;
				};
				meta: object;
				errorShape: import("@trpc/server").TRPCDefaultErrorShape;
				transformer: false;
			}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
				get: import("@trpc/server").TRPCMutationProcedure<{
					input: {
						marketplaceId: string;
						asin: string;
						startAt?: unknown;
						endAt?: unknown;
						limit?: unknown;
						days?: unknown;
						metrics?: ("bsr" | "price")[] | undefined;
						bucket?: "auto" | "day" | "week" | "month" | undefined;
					};
					output: ProductReadModel;
					meta: object;
				}>;
				getSummary: import("@trpc/server").TRPCMutationProcedure<{
					input: {
						marketplaceId: string;
						asin: string;
					};
					output: ProductInfo;
					meta: object;
				}>;
				getHistory: import("@trpc/server").TRPCMutationProcedure<{
					input: {
						marketplaceId: string;
						asin: string;
						startAt?: unknown;
						endAt?: unknown;
						limit?: unknown;
						days?: unknown;
						metrics?: ("bsr" | "price")[] | undefined;
						bucket?: "auto" | "day" | "week" | "month" | undefined;
						format?: "legacy" | "agent" | undefined;
					};
					output: AgentHistoryResponse | {
						marketplaceId: string;
						asin: string;
						metric: "bsrMain";
						latestImportAt: string | null;
						categoryNames: Record<string, string>;
						points: {
							categoryId: number;
							categoryName: string | null;
							observedAt: string;
							keepaMinutes: number;
							value: number | null;
							isMissing: boolean;
						}[];
						collecting: boolean;
						syncTriggered: boolean;
						operation: PublicOperation | null;
					} | {
						collecting: boolean;
						syncTriggered: boolean;
						operation: PublicOperation | null;
						marketplaceId: string;
						asin: string;
						metric: "bsrMain" | "bsrCategory" | "priceAmazon" | "priceNew" | "priceNewFba";
						latestImportAt: string | null;
						categoryNames: {
							[x: string]: string;
						};
						points: {
							categoryId: number;
							categoryName: string;
							observedAt: string;
							keepaMinutes: number;
							value: number | null;
							isMissing: boolean;
						}[];
					};
					meta: object;
				}>;
			}>>;
			operation: import("@trpc/server").TRPCBuiltRouter<{
				ctx: {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: {
						key: string;
						data: LicenseUsageData | undefined;
					};
					licenseError: undefined;
					request: ContextRequest;
				} | {
					user: null;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: null;
					licenseError: string | undefined;
					request: ContextRequest;
				} | {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: number;
					license: null;
					licenseError: undefined;
					request: ContextRequest;
				};
				meta: object;
				errorShape: import("@trpc/server").TRPCDefaultErrorShape;
				transformer: false;
			}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
				get: import("@trpc/server").TRPCQueryProcedure<{
					input: {
						id: string;
					};
					output: PublicOperation;
					meta: object;
				}>;
			}>>;
			dev: import("@trpc/server").TRPCBuiltRouter<{
				ctx: {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: {
						key: string;
						data: LicenseUsageData | undefined;
					};
					licenseError: undefined;
					request: ContextRequest;
				} | {
					user: null;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: null;
					licenseError: string | undefined;
					request: ContextRequest;
				} | {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: number;
					license: null;
					licenseError: undefined;
					request: ContextRequest;
				};
				meta: object;
				errorShape: import("@trpc/server").TRPCDefaultErrorShape;
				transformer: false;
			}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
				createClerkSignInToken: import("@trpc/server").TRPCMutationProcedure<{
					input: void;
					output: {
						ticket: string;
						expiresInSeconds: number;
					};
					meta: object;
				}>;
			}>>;
			license: import("@trpc/server").TRPCBuiltRouter<{
				ctx: {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: {
						key: string;
						data: LicenseUsageData | undefined;
					};
					licenseError: undefined;
					request: ContextRequest;
				} | {
					user: null;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: null;
					license: null;
					licenseError: string | undefined;
					request: ContextRequest;
				} | {
					user: ClerkUser;
					isAdmin: boolean;
					authType: "license" | "clerk" | "none";
					authExpiresAtMs: number;
					license: null;
					licenseError: undefined;
					request: ContextRequest;
				};
				meta: object;
				errorShape: import("@trpc/server").TRPCDefaultErrorShape;
				transformer: false;
			}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
				validate: import("@trpc/server").TRPCMutationProcedure<{
					input: void;
					output: {
						email: string;
						usage: number;
						usageLimit: number;
					};
					meta: object;
				}>;
				status: import("@trpc/server").TRPCMutationProcedure<{
					input: void;
					output: {
						email: string;
						usage: number;
						usageLimit: number;
					};
					meta: object;
				}>;
			}>>;
		}>>;
	}>>;
}>>;
export type PublicAppRouter = typeof publicAppRouter;

export {};
